# Generated by Django 5.0.2 on 2024-02-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='stage',
            field=models.IntegerField(verbose_name='Etapa'),
        ),
    ]
